In [1]:
import numpy
import urllib
import scipy.optimize
import random

In [24]:
def parseData(fname):
    for l in urllib.urlopen(fname):
        yield eval(l) 

# eval:将字符串string对象转化为有效的表达式参与求值运算返回计算结果,可以把list,tuple,dict和string相互转化。
          
print "Reading data..."
data = list(parseData("http://jmcauley.ucsd.edu/cse190/data/beer/beer_50000.json"))
print "done"
        

Reading data...
done


## Real-valued features

In [19]:
data = [d for d in data if 'user/ageInSeconds' in d and d['user/ageInSeconds'] < 60*60*24*365*80]

def feature(datum):
    feat = [1,datum['user/ageInSeconds'],datum['user/ageInSeconds']**2]
    return feat

X = [feature(d) for d in data]
X[:10]
y = [d['review/overall'] for d in data]
y[:10]

theta,residuals,rank,s = numpy.linalg.lstsq(X, y)
#Return the least-squares solution to a linear matrix equation.

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if sys.path[0] == '':


In [20]:
theta

array([ 9.59164997e-18,  6.18514388e-09, -2.32130867e-18])

In [26]:
data[4]

{'beer/ABV': 7.7,
 'beer/beerId': '64883',
 'beer/brewerId': '1075',
 'beer/name': 'Cauldron DIPA',
 'beer/style': 'American Double / Imperial IPA',
 'review/appearance': 4.0,
 'review/aroma': 4.5,
 'review/overall': 4.0,
 'review/palate': 4.0,
 'review/taste': 4.5,
 'review/text': "According to the website, the style for the Caldera Cauldron changes every year. The current release is a DIPA, which frankly is the only cauldron I'm familiar with (it was an IPA/DIPA the last time I ordered a cauldron at the horsebrass several years back). In any event... at the Horse Brass yesterday.\t\tThe beer pours an orange copper color with good head retention and lacing. The nose is all hoppy IPA goodness, showcasing a huge aroma of dry citrus, pine and sandlewood. The flavor profile replicates the nose pretty closely in this West Coast all the way DIPA. This DIPA is not for the faint of heart and is a bit much even for a hophead like myslf. The finish is quite dry and hoppy, and there's barely eno

In [18]:
X = numpy.matrix(X)
y = numpy.matrix(y)
numpy.linalg.inv(X.T * X) * X.T * y.T

matrix([[3.90290031e+00],
        [7.61015628e-12]])

## Categorical features

In [28]:
data2 = [d for d in data if d.has_key('user/gender')]

def feature(datum):
  feat = [1]
  if datum['user/gender'] == "Male":
    feat.append(0)
  else:
    feat.append(1)
  return feat

X = [feature(d) for d in data2]
y = [d['review/overall'] for d in data2]
theta,residuals,rank,s = numpy.linalg.lstsq(X, y)

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:13: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  del sys.path[0]


In [22]:
theta

array([3.91189602, 0.19167541])

In [29]:
X[:10]

[[1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0]]

## Random features

In [25]:
def feature(datum):
  feat = [1] + [random.random() for i in range(100)]
  return feat

X =[feature(d) for d in data ]
X[:10]


[[1,
  0.3040580333619598,
  0.5967064480691784,
  0.5881434176286666,
  0.5827267959379866,
  0.42968024173272235,
  0.9545519653939722,
  0.6873501976235806,
  0.6661160196681816,
  0.31188517824977313,
  0.3620612520031623,
  0.30833984574186823,
  0.4201552941319796,
  0.44254846363815703,
  0.5527768443376762,
  0.9061759932776704,
  0.14744406063630644,
  0.6543225377593125,
  0.31414414170642857,
  0.5251945432459908,
  0.04762540007746563,
  0.9284169888539844,
  0.8104908155201608,
  0.6382845623950898,
  0.6257058824767425,
  0.4353801550190729,
  0.21458597813068825,
  0.30931231376513635,
  0.5122028464025554,
  0.9476401805554006,
  0.6398701391405545,
  0.04201126897529772,
  0.13018857462352373,
  0.26266388546351593,
  0.738143736084894,
  0.9572753448439588,
  0.5543944966169307,
  0.38789536759135146,
  0.9103759894802096,
  0.7026114089097975,
  0.8314907153093409,
  0.8106672790015935,
  0.20844254902169845,
  0.2071311897758451,
  0.08554474277088164,
  0.114711490

## Regression Diagnostics 

In [30]:
(residuals/len(y)) #mse

array([0.4818291])